### ISSUE TITLE
Grammar: always leave a space BEFORE '("

### ISSUE THREAD

**Issue by jbrucker** [PlanMeProject/PlanMeDocumentation#13]
In your Use Case document, Development Plan, API Endpoints, and maybe others there are several places where you write like this:
```
API Endpoints(Postman)
```
In English text, leave a space before "(".  I can't think of any exceptions to this.
```
API Endpoints (Postman)
```

In your Retrospectives, you *did* leave a space (correct).

**Comment by D7NAMITE** [comment]
Thank you for pointing out all these mistakes. I've scanned through our documents and fixed all I've detected.
