### ISSUE TITLE
Not Using Your Own Coding Guide

### ISSUE THREAD

**Issue by jbrucker** [PlanMeProject/PlanMeDocumentation#9]
https://github.com/PlanMeProject/PlanMeDocumentation/wiki/Coding-Guide

Your coding guide says you will use TAB instead of spaces.

I checked out your code and immediately found Python files created
by you (not generated by Django) using spaces not tabs.

**Comment by D7NAMITE** [comment]
We've looked into the indentation in our project. Unfortunately for us, it seems like our IDE was configured to translate all the `TAB` to the spaces even though we press `TAB` on our code.
As our works are about to reach the deployment state our team has concluded that we will change our guide to use the 4-space indentation instead.

Thanks for pointing this out!
